	SELECT  ALBUM.ALBUM_NAME, ARTIST.ARTIST_NAME, TRACK.TRACK_NAME, ARTIST.ARTIST_IMG,
    ARTIST.ARTIST_DESCRIPTION, ALBUM.ALBUM_IMG, ALBUM.NO_OF_TRACKS,
    GENRE.GENRE_NAME,  ALBUM.YEAR, TRACK.TRACK_NAME, ALBUM_TRACKS.TRACKNO,
    VINYL_PRODUCT.VINYL_ID, CD_PRODUCT.CD_ID, ALBUM_MP3.MP3_ID, TRACK_MP3.MP3_ID,
    TRACK.TRACK_ID, ALBUM.ALBUM_ID, VINYL_PRODUCT.VINYLPRODUCT_ID, CD_PRODUCT.CDPRODUCT_ID,
    ALBUM_MP3_PRODUCT.ALBUM_MP3_PRODUCT_ID, TRACK_MP3_PRODUCT.TRACK_MP3_PRODUCT_ID
	FROM ALBUM
	INNER JOIN ARTIST
	ON ALBUM.ARTIST_ID = ARTIST.ARTIST_ID
	INNER JOIN ALBUM_TRACKS
	ON ALBUM.ALBUM_ID = ALBUM_TRACKS.ALBUM_ID
	INNER JOIN TRACK
	ON ALBUM_TRACKS.TRACK_ID = TRACK.TRACK_ID
	INNER JOIN GENRE
	ON ALBUM.GENRE_ID = GENRE.GENRE_ID
    LEFT JOIN ALBUM_VINYL
    ON ALBUM_VINYL.ALBUM_ID = ALBUM.ALBUM_ID    
    LEFT JOIN ALBUM_CD
    ON ALBUM_CD.ALBUM_ID = ALBUM.ALBUM_ID    
    LEFT JOIN ALBUM_MP3
    ON ALBUM_MP3.ALBUM_ID = ALBUM.ALBUM_ID
    LEFT JOIN TRACK_MP3
    ON TRACK_MP3.MP3_ID = TRACK.TRACK_ID
    LEFT JOIN VINYL_PRODUCT
    ON VINYL_PRODUCT.VINYL_ID = ALBUM_VINYL.VINYL_ID
    LEFT JOIN CD_PRODUCT
    ON CD_PRODUCT.CD_ID = ALBUM_CD.CD_ID
    LEFT JOIN ALBUM_MP3_PRODUCT
    ON ALBUM_MP3_PRODUCT.MP3_ID = ALBUM_MP3.MP3_ID
    LEFT JOIN TRACK_MP3_PRODUCT
    ON TRACK_MP3_PRODUCT.MP3_ID = TRACK_MP3.MP3_ID
    INNER JOIN PRODUCT
    ON PRODUCT.PRODUCT_ID = VINYL_PRODUCT.VINYLPRODUCT_ID
	WHERE PRODUCT_ID = 5
	