SELECT DISTINCT PRODUCT.PRODUCT_ID, PRODUCT.TYPE, PRICE, ALBUM_NAME, ARTIST_NAME, ALBUM_IMG
FROM PRODUCT
JOIN ALBUM_RELEASE
ON PRODUCT.PRODUCT_ID = ALBUM_RELEASE.ALBUM_PRODUCT_ID
JOIN ALBUM
ON ALBUM.ALBUM_ID = ALBUM_RELEASE.ALBUM_ID
JOIN ARTIST
ON ARTIST.ARTIST_ID = ALBUM.ARTIST_ID
WHERE PRODUCT_ID= '1' LIMIT 1;
