SELECT * FROM PRODUCT
LEFT JOIN VINYL_PRODUCT
ON VINYL_PRODUCT.VINYLPRODUCT_ID = PRODUCT.PRODUCT_ID
LEFT JOIN CD_PRODUCT
ON CD_PRODUCT.CDPRODUCT_ID = PRODUCT.PRODUCT_ID
LEFT JOIN ALBUM_MP3_PRODUCT
ON ALBUM_MP3_PRODUCT.ALBUM_MP3_PRODUCT_ID = PRODUCT.PRODUCT_ID
LEFT JOIN TRACK_MP3_PRODUCT
ON TRACK_MP3_PRODUCT.TRACK_MP3_PRODUCT_ID = PRODUCT.PRODUCT_ID
LEFT JOIN ALBUM_VINYL
ON VINYL_PRODUCT.VINYL_ID = ALBUM_VINYL.VINYL_ID
LEFT JOIN ALBUM_CD
ON CD_PRODUCT.CD_ID = ALBUM_CD.CD_ID
LEFT JOIN ALBUM_MP3
ON ALBUM_MP3_PRODUCT.MP3_ID = ALBUM_MP3.MP3_ID
LEFT JOIN TRACK_MP3
ON TRACK_MP3_PRODUCT.MP3_ID = TRACK_MP3.MP3_ID
LEFT JOIN ALBUM
ON ALBUM_CD.ALBUM_ID = ALBUM.ALBUM_ID
LEFT JOIN ALBUM_CD
AS ALBUM2 ON ALBUM_VINYL.ALBUM_ID
LEFT JOIN ALBUM
AS ALBUM3 ON ALBUM_MP3.ALBUM_ID
GROUP BY PRODUCT_ID;